/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorMantenimientoEstudiate;
import Controlador.Validador;
import Modelo.BDEstudiante;
import Modelo.EstudianteException;
import javax.swing.JLabel;
import javax.swing.JTextField;

//En esta clase se encuentra
public class ManipulaEstudiantes extends javax.swing.JFrame {

    private ControladorMantenimientoEstudiate cme;
    private Validador validate;

    public ManipulaEstudiantes(BDEstudiante db) {
        initComponents();
        cme = new ControladorMantenimientoEstudiate(this, db);
        this.guiBotones1.agregarEvento(cme);
        validate = new Validador();
    }

    public int getCodigoPorFuente(Object object) {
          return this.guiBotones1.getCodigoPorFuente(object);
    }

  


public void setTexCarnet(String texCarnet) {
        this.texCarnet.setText(texCarnet);
    }

    public void setTexCorreo(String texCorreo) {
        this.texCorreo.setText(texCorreo);
    }

    public void setTexNombre(String texNombre) {
        this.texNombre.setText(texNombre);
    }

    public String getTexCarnet() {
        return this.texCarnet.getText();
    }

    public String getTexCorreo() {
        return this.texCorreo.getText();
    }

    public String getTexNombre() {
        return this.texNombre.getText();
    }


    public void setTexNombre(JTextField texNombre) {
        this.texNombre = texNombre;
    }

    public boolean verificar() throws EstudianteException {
        boolean escarnet = verificarTexCarnet();
                    
        if ((this.texCarnet.getText().equals("") || this.texCorreo.getText().equals("")) || this.texCorreo.getText().equals("")) {
        
          return true;
        }
            
        return false;
    }
     public boolean verificarTexCarnet() throws EstudianteException {
 
         boolean escarnet = validate.validarCarnet(this.texCarnet.getText());
         if(!escarnet){
             throw new EstudianteException("Formato inválido de carnet", 
                     false);
         }
         
         return !escarnet;
    }
     
     public void setEditable(boolean re){
         this.texCarnet.setEditable(re);
     }
     /**public void setText(String nombre, String carnet, String correo){
      
        texCarnet.setText(carnet);
        texNombre.setText(nombre);
        texCorreo.setText(correo);
    }*/
     

    public void limpiar() {
        this.texCarnet.setText("");
        this.texNombre.setText("");
        this.texCorreo.setText("");
    }

    public void setMensajes(String mensajes) {
        this.Mensajes.setText(mensajes);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guiBotones1 = new Vista.GuiBotones();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        texCarnet = new javax.swing.JTextField();
        texNombre = new javax.swing.JTextField();
        texCorreo = new javax.swing.JTextField();
        Mensajes = new javax.swing.JLabel();

        jLabel1.setText("Carnet");

        jLabel2.setText("Nombre");

        jLabel3.setText("Correo");

        texCarnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texCarnetActionPerformed(evt);
            }
        });

        texNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(texCarnet, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(texNombre)
                    .addComponent(texCorreo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(texCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(texNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(texCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guiBotones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(202, 202, 202))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(231, Short.MAX_VALUE)
                .addComponent(Mensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Mensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guiBotones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texCarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texCarnetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texCarnetActionPerformed

    private void texNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texNombreActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Mensajes;
    private Vista.GuiBotones guiBotones1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField texCarnet;
    private javax.swing.JTextField texCorreo;
    private javax.swing.JTextField texNombre;
    // End of variables declaration//GEN-END:variables
}
